### ISSUE TITLE
Albumモデルの気になった点

### ISSUE THREAD

**Issue by toyokappa** [kawaPC/px100#1]
https://github.com/kawaPC/px100/blob/60903b3dcd71c551dc02e37e832635aa2ec96582/app/models/album.rb#L7-L9

こちら、`validates`の間に`mount_uploader`を定義していますが、何か意図はありますか？
関連は関連、バリデーションはバリデーションといった感じで、種類別にまとめて書くのが通常かなぁと思います。

```ruby
has_many xxx
has_many xxx
belongs_to xxx

validates xxx
validates xxx
validate xxx

mount_uploader xxx

~~~(以下略)~~~
```

**Comment by toyokappa** [comment]
https://github.com/kawaPC/px100/blob/60903b3dcd71c551dc02e37e832635aa2ec96582/app/models/album.rb#L11-L15

同じインデントで引数を書いていますが、メソッドを書いているのか、引数を書いているのかが非常に見づらいです。引数を改行で書く場合はインデントを入れるようにしましょう。

**Comment by toyokappa** [comment]
https://github.com/kawaPC/px100/blob/60903b3dcd71c551dc02e37e832635aa2ec96582/app/models/album.rb#L18-L20

このメソッドはなにか意味がありますか？

**Comment by kawaPC** [comment]
ありがとうございます！
以下のように修正してみました。

https://github.com/kawaPC/px100/blob/4581cac3b63f1ae7d20d6a4839d032cde87fd490/app/models/album.rb#L2-L15

to_paramについてですが、おっしゃる通り現状働いてないメソッドになっていたので除外しました。
